### ISSUE TITLE
Script leaks sensitive data

### ISSUE THREAD

**Issue by CosmicRaichu** [EwanCroft/bean-dumper#1]
It keeps spilling the beans

**Comment by EwanCroft** [comment]
Leaks sensitive data? How? Or am I missing a joke?

**Comment by CosmicRaichu** [comment]
It's a silly joke. 'Spill the beans' is an english idiom for revealing a secret :p

**Comment by EwanCroft** [comment]
Oooh.

I _knew_ that idiom, I just was confused by the issue's title. I'm an idiot lol.
